# -*- coding: utf-8 -*-
"""Python_Tuples_and_Sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjLyJfllMVJCVFVbzoka-xcKm0JoAQI4

# Tuple
## ordered collection of items - similar or dissimilar items
# Immutable
"""

marks=(98,68,78,78.5)
print(marks)

# create a tuple with different datatypes
stud_info=(101,"Rahul",9.2,"CSE")
print(stud_info)

# create a tuple for subjects
subjects=("Python","OS","DSV","Statistics","SQL","Machine Learning")
print(subjects)
#access through index
print("Element present in 2nd Index",subjects[2])
print("Element Displaying in the negative index:",subjects[-2])


# Slicing
print (subjects[:3])
print(subjects[3:5])
print(subjects[4:])

# tuple with nested
students_info=(101,"chirag",(87,89,95))
print(students_info)
print(students_info[1])
print(students_info[2][1])

print(len(students_info))

# checking the element present in tuple or not
print("SQL"in subjects)

# if elements not in tuple
print("Mathematics"in subjects)

# Create a list using square brackets
students_info = [101, 'chirag', (87, 89, 95)]

print(students_info[2][1])
print(students_info)

# Now .remove() works perfectly
students_info.remove(101)
print(students_info)

"""#SET
## unordered collection of items
## No duplications
### always it gives the result of unique values
### symbol for creating set{}
## mutable, but it won't support the index
"""

# create the set
student=(101,"Kiran","CSE",8.7)
print(student)

stud_names={"Manish","Ravi","Teja","Ashwin","Manish","Kiran","Karan","Teja"}
print(stud_names)

# Create a set using curly braces
stud_info = {101, "Manish", "CSE", 21, 8.5}

# Remove an item (works perfectly)
stud_info.remove(21)
print(stud_info)

# WARNING: .remove(102) will cause a KeyError because 102 is not in the set.
# Use .discard(102) instead if you want to avoid errors when an item is missing.
stud_info.discard(102)
print(stud_info)

# Discard an item (works without errors)
stud_info.discard("Manish")
print(stud_info)

# clear the set
marks={78,98,78,67,95}
print(marks)
marks.clear()
print(marks)

#delete the set

#print(marks)
#del

"""# SET Operations
## 1. Union
## 2. Intersection
## 3. Difference
## 4.Complement
## 5.Subset,superset,disjoint
"""

# Create two sets
python_students = {"Rahul", "Vani", "Manish", "Anil", "Chirag"}
java_students = {"Manish", "Lalith", "Anil", "Ranjith", "Sanjiv"}

# 1. Union operation
result = python_students.union(java_students)
print("Union Operations:", result)

# 2. Intersection operation
result_inter = python_students.intersection(java_students)
print("Result of Intersection operation:", result_inter)

# 3. Difference operation (इसका रिजल्ट अब प्रिंट होगा)
result_diff = python_students.difference(java_students)
print("Result of Difference operation:", result_diff)

#converting list to set
rollno={101,102,103,105,104,101,106,102}
unique_rollno=set(rollno)
unique_rollno_list=list(unique_rollno)
print(unique_rollno_list)